version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_UNIVERSITY_NAME=University of Tasmania
      - NEXT_PUBLIC_MODULE_CODE=UPP014
      - NEXT_PUBLIC_MODULE_NAME=Writing in Practice
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network
    restart: unless-stopped
    command: npm run dev

networks:
  app-network:
    driver: bridge
