services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_UNIVERSITY_NAME=University of Tasmania
      - NEXT_PUBLIC_MODULE_CODE=UPP014
      - NEXT_PUBLIC_MODULE_NAME=Writing in Practice
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/chat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Placeholder for future backend service
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - NODE_ENV=production
  #   networks:
  #     - app-network
  #   restart: unless-stopped
  #   depends_on:
  #     - database

  # Placeholder for database service
  # database:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_DB=utas_writing_practice
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network
  #   restart: unless-stopped

networks:
  app-network:
    driver: bridge

# volumes:
#   postgres_data:
